export * from "./CreateMessage";
export const jurusan = [
  "Pendidikan Masyarakat | FKIP",
  "Pendidikan Bahasa Indonesia | FKIP",
  "Pendidikan Bahasa Inggris | FKIP",
  "Pendidikan Matematika | FKIP",
  "Pendidikan Biologi | FKIP",
  "Pendidikan Ekonomi | FKIP",
  "Pendidikan Geografi | FKIP",
  "Pendidikan Jasmani | FKIP",
  "Pendidikan Sejarah | FKIP",
  "Pendidikan Fisika | FKIP",
  "Pendidikan Profesi Guru | FKIP",
  "Ekonomi Pembangunan | FEB",
  "Manajemen | FEB",
  "Akuntansi | FEB",
  "Keuangan dan Perbankan | FEB",
  "Teknik Sipil | FT",
  "Teknik Elektro | FT",
  "Informatika | FT",
  "Sistem Informasi | FT",
  "Ekonomi Syariah | FAI",
  "Manajemen Mutu Halal | FAI",
  "Kesehatan Masyarakat | FIK",
  "Gizi | FIK",
  "Ilmu Politik | FISIP",
  "Agroteknologi | FP",
  "Agribisnis | FP",
  "Teknologi Pangan dan Hasil Pertanian | FP",
];

export const angkatan = [
  "2002",
  "2003",
  "2004",
  "2005",
  "2006",
  "2007",
  "2008",
  "2009",
  "2010",
  "2011",
  "2012",
  "2013",
  "2014",
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
  "2024",
];
